" Name:         Pole
" Author:       https://github.com/Alvarocz/
" Maintainer:   Gianmaria Bajo <mg1979.git@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: sab 27 mar 2021 19:56:02 CET

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'pole'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#25262e', '#800000', '#008000', '#ca9d81', '#58678c', '#ad85cc', '#008080', '#caccd7', '#626870', '#ee6a6a', '#54ca91', '#f0c674', '#8599cc', '#ff00ff', '#54c5ca', '#d5d6d7']
  if has('nvim')
    let g:terminal_color_0 = '#25262e'
    let g:terminal_color_1 = '#800000'
    let g:terminal_color_2 = '#008000'
    let g:terminal_color_3 = '#ca9d81'
    let g:terminal_color_4 = '#58678c'
    let g:terminal_color_5 = '#ad85cc'
    let g:terminal_color_6 = '#008080'
    let g:terminal_color_7 = '#caccd7'
    let g:terminal_color_8 = '#626870'
    let g:terminal_color_9 = '#ee6a6a'
    let g:terminal_color_10 = '#54ca91'
    let g:terminal_color_11 = '#f0c674'
    let g:terminal_color_12 = '#8599cc'
    let g:terminal_color_13 = '#ff00ff'
    let g:terminal_color_14 = '#54c5ca'
    let g:terminal_color_15 = '#d5d6d7'
  endif
  hi Normal guifg=#a2a8ad guibg=#25262e gui=NONE cterm=NONE
  let g:Vsd = get(g:, 'Vsd', {})
  silent! call vsd#init('pole')
  hi Comment guifg=#626870 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#ff9800 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#ee6a6a guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#ff9800 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#54ca91 guibg=NONE gui=bold cterm=bold
  hi Boolean guifg=#d5d6d7 guibg=NONE gui=bold cterm=bold
  hi Float guifg=#54ca91 guibg=NONE gui=bold cterm=bold
  hi Identifier guifg=#659ea2 guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#8599cc guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#d5d6d7 guibg=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#d5d6d7 guibg=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#8599cc guibg=NONE gui=NONE cterm=NONE
  hi Label guifg=#58678c guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#58678c guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#d5d6d7 guibg=NONE gui=NONE cterm=NONE
  hi Exception guifg=#8599cc guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#008080 guibg=NONE gui=bold cterm=NONE
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi Type guifg=#ad85cc guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#58678c guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#8599cc guibg=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#58678c guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#3b4d61 guibg=NONE gui=NONE cterm=NONE
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link SpecialComment Special
  hi Delimiter guifg=#626870 guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#f0c674 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#d5d6d7 guibg=#384048 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#384048 gui=NONE cterm=NONE
  hi PmenuSel guifg=#25262e guibg=#54ca91 gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#54ca91 gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#23242a gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#23242a gui=NONE cterm=NONE
  hi CursorLineNr guifg=#54c5ca guibg=#23242a gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#23242a gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=#58678c gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#384048 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#25262e guibg=#ee6a6a gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ee6a6a guibg=NONE gui=bold cterm=bold
  hi Ignore guifg=#384048 guibg=NONE gui=NONE cterm=NONE
  hi Builtin guifg=#ad85cc guibg=NONE gui=bold cterm=bold
  hi Import guifg=#d5d6d7 guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#d5d6d7 guibg=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#ff00ff guibg=#384048 gui=bold cterm=bold
  hi LineNr guifg=#384048 guibg=#23242a gui=NONE cterm=NONE
  hi MatchParen guifg=#f0c674 guibg=NONE gui=bold cterm=bold
  hi Question guifg=#f0c674 guibg=NONE gui=bold cterm=bold
  hi Search guifg=#54c5ca guibg=#3b4d61 gui=bold cterm=bold
  hi SpecialKey guifg=#f0c674 guibg=#23242a gui=NONE cterm=NONE
  hi StatusLine guifg=#d5d6d7 guibg=#23242a gui=NONE cterm=NONE
  hi StatusLineNC guifg=#626870 guibg=#23242a gui=NONE cterm=NONE
  hi TabLine guifg=#25262e guibg=#626870 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#626870 gui=NONE cterm=NONE
  hi TabLineSel guifg=#d5d6d7 guibg=NONE gui=NONE cterm=NONE
  hi Title guifg=#d5d6d7 guibg=NONE gui=bold cterm=bold
  hi VertSplit guifg=#384048 guibg=#23242a gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#23242a gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#384048 gui=NONE cterm=NONE
  hi Folded guifg=#808080 guibg=#282d33 gui=italic cterm=italic
  hi FoldColumn guifg=#58678c guibg=#23242a gui=italic cterm=italic
  hi Conceal guifg=#808080 guibg=#23242a gui=italic cterm=italic
  hi NonText guifg=#384048 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#f0c674 guibg=#58678c gui=bold cterm=bold
  hi SpellBad guifg=#ee6a6a guibg=NONE gui=undercurl cterm=undercurl
  hi SpellCap guifg=#54ca91 guibg=NONE gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#8599cc guibg=NONE gui=undercurl cterm=undercurl
  hi SpellRare guifg=#ad85cc guibg=NONE gui=undercurl cterm=undercurl
  hi DiffDelete guifg=#800000 guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Folded gui=NONE cterm=NONE
    hi FoldColumn gui=NONE cterm=NONE
    hi Conceal gui=NONE cterm=NONE
  endif
  hi DiffAdd    guifg=NONE guibg=#1E3C25 ctermfg=NONE ctermbg=23
  hi DiffChange guifg=NONE guibg=#1E1F51 ctermfg=NONE ctermbg=17
  hi DiffText   guifg=NONE guibg=#421F25 ctermfg=NONE ctermbg=52
  hi diffAdded guifg=#54ca91 guibg=NONE gui=NONE cterm=NONE
  hi diffChanged guifg=#ca9d81 guibg=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#ee6a6a guibg=NONE gui=NONE cterm=NONE
  hi diffDiffer guifg=#ca9d81 guibg=NONE gui=bold cterm=bold
  hi diffFile guifg=#ad85cc guibg=NONE gui=bold cterm=bold
  hi diffLine guifg=#f0c674 guibg=NONE gui=italic cterm=italic
  hi GitGutterAdd guifg=#54ca91 guibg=#23242a gui=NONE cterm=NONE
  hi GitGutterChange guifg=#ca9d81 guibg=#23242a gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#ca9d81 guibg=#23242a gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ee6a6a guibg=#23242a gui=NONE cterm=NONE
  hi SignifySignAdd guifg=#54ca91 guibg=#23242a gui=NONE cterm=NONE
  hi SignifySignChange guifg=#ca9d81 guibg=#23242a gui=NONE cterm=NONE
  hi SignifySignChangeDelete guifg=#ca9d81 guibg=#23242a gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#ee6a6a guibg=#23242a gui=NONE cterm=NONE
  if !s:italics
    hi diffLine gui=NONE cterm=NONE
  endif
  if get(g:Vsd, 'extra_highlight', 1)
    hi! link helpCommand Type
    hi! link helpSectionDelim PreProc
    hi! link helpHeader PreProc
    hi! link helpHeadline Statement
    hi! link helpHyperTextEntry String
    hi! link helpHyperTextJump Identifier
    hi! link helpExample Comment
    hi! link helpOption Type
    hi! link helpSpecial Special
    hi htmlTag guifg=#626870 guibg=NONE gui=NONE cterm=NONE
    hi htmlTagName guifg=#ad85cc guibg=NONE gui=NONE cterm=NONE
    hi htmlArg guifg=#d5d6d7 guibg=NONE gui=NONE cterm=NONE
    hi pythonBytesEscape guifg=#008080 guibg=NONE gui=NONE cterm=NONE
    hi pythonStrFormat guifg=#008080 guibg=NONE gui=NONE cterm=NONE
    hi pythonStrFormatting guifg=#008080 guibg=NONE gui=NONE cterm=NONE
    hi cSpecial guifg=#008080 guibg=NONE gui=NONE cterm=NONE
    hi! link cBraces Delimiter
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=248 ctermbg=235 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  let g:Vsd = get(g:, 'Vsd', {})
  silent! call vsd#init('pole')
  hi Comment ctermfg=242 ctermbg=NONE cterm=italic
  hi Constant ctermfg=208 ctermbg=NONE cterm=NONE
  hi String ctermfg=203 ctermbg=NONE cterm=NONE
  hi Character ctermfg=208 ctermbg=NONE cterm=NONE
  hi Number ctermfg=42 ctermbg=NONE cterm=bold
  hi Boolean ctermfg=188 ctermbg=NONE cterm=bold
  hi Float ctermfg=42 ctermbg=NONE cterm=bold
  hi Identifier ctermfg=73 ctermbg=NONE cterm=NONE
  hi Function ctermfg=103 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=188 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=188 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=103 ctermbg=NONE cterm=NONE
  hi Label ctermfg=60 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=60 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=188 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=103 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=6 ctermbg=NONE cterm=NONE
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi Type ctermfg=140 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=60 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=103 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=60 ctermbg=NONE cterm=NONE
  hi Special ctermfg=238 ctermbg=NONE cterm=NONE
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link SpecialComment Special
  hi Delimiter ctermfg=242 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=222 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=188 ctermbg=238 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=238 cterm=NONE
  hi PmenuSel ctermfg=235 ctermbg=42 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=42 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=80 ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=60 cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=NONE cterm=NONE
  hi Error ctermfg=235 ctermbg=203 cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=bold
  hi Ignore ctermfg=238 ctermbg=NONE cterm=NONE
  hi Builtin ctermfg=140 ctermbg=NONE cterm=bold
  hi Import ctermfg=188 ctermbg=NONE cterm=NONE
  hi Include ctermfg=188 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=13 ctermbg=238 cterm=bold
  hi LineNr ctermfg=238 ctermbg=235 cterm=NONE
  hi MatchParen ctermfg=222 ctermbg=NONE cterm=bold
  hi Question ctermfg=222 ctermbg=NONE cterm=bold
  hi Search ctermfg=80 ctermbg=238 cterm=bold
  hi SpecialKey ctermfg=222 ctermbg=235 cterm=NONE
  hi StatusLine ctermfg=188 ctermbg=235 cterm=NONE
  hi StatusLineNC ctermfg=242 ctermbg=235 cterm=NONE
  hi TabLine ctermfg=235 ctermbg=242 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=242 cterm=NONE
  hi TabLineSel ctermfg=188 ctermbg=NONE cterm=NONE
  hi Title ctermfg=188 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=238 ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
  hi Folded ctermfg=8 ctermbg=236 cterm=italic
  hi FoldColumn ctermfg=60 ctermbg=235 cterm=italic
  hi Conceal ctermfg=8 ctermbg=235 cterm=italic
  hi NonText ctermfg=238 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=222 ctermbg=60 cterm=bold
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=42 ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=103 ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=140 ctermbg=NONE cterm=undercurl
  hi DiffDelete ctermfg=1 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi Folded cterm=NONE
    hi FoldColumn cterm=NONE
    hi Conceal cterm=NONE
  endif
  hi DiffAdd    guifg=NONE guibg=#1E3C25 ctermfg=NONE ctermbg=23
  hi DiffChange guifg=NONE guibg=#1E1F51 ctermfg=NONE ctermbg=17
  hi DiffText   guifg=NONE guibg=#421F25 ctermfg=NONE ctermbg=52
  hi diffAdded ctermfg=42 ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=180 ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=203 ctermbg=NONE cterm=NONE
  hi diffDiffer ctermfg=180 ctermbg=NONE cterm=bold
  hi diffFile ctermfg=140 ctermbg=NONE cterm=bold
  hi diffLine ctermfg=222 ctermbg=NONE cterm=italic
  hi GitGutterAdd ctermfg=42 ctermbg=235 cterm=NONE
  hi GitGutterChange ctermfg=180 ctermbg=235 cterm=NONE
  hi GitGutterChangeDelete ctermfg=180 ctermbg=235 cterm=NONE
  hi GitGutterDelete ctermfg=203 ctermbg=235 cterm=NONE
  hi SignifySignAdd ctermfg=42 ctermbg=235 cterm=NONE
  hi SignifySignChange ctermfg=180 ctermbg=235 cterm=NONE
  hi SignifySignChangeDelete ctermfg=180 ctermbg=235 cterm=NONE
  hi SignifySignDelete ctermfg=203 ctermbg=235 cterm=NONE
  if !s:italics
    hi diffLine cterm=NONE
  endif
  if get(g:Vsd, 'extra_highlight', 1)
    hi! link helpCommand Type
    hi! link helpSectionDelim PreProc
    hi! link helpHeader PreProc
    hi! link helpHeadline Statement
    hi! link helpHyperTextEntry String
    hi! link helpHyperTextJump Identifier
    hi! link helpExample Comment
    hi! link helpOption Type
    hi! link helpSpecial Special
    hi htmlTag ctermfg=242 ctermbg=NONE cterm=NONE
    hi htmlTagName ctermfg=140 ctermbg=NONE cterm=NONE
    hi htmlArg ctermfg=188 ctermbg=NONE cterm=NONE
    hi pythonBytesEscape ctermfg=6 ctermbg=NONE cterm=NONE
    hi pythonStrFormat ctermfg=6 ctermbg=NONE cterm=NONE
    hi pythonStrFormatting ctermfg=6 ctermbg=NONE cterm=NONE
    hi cSpecial ctermfg=6 ctermbg=NONE cterm=NONE
    hi! link cBraces Delimiter
  endif
  hi Folded ctermfg=8 ctermbg=235 cterm=italic
  if !s:italics
    hi Folded cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color:	background	#25262e		235	Black
" Color:	darkred		#800000		1	DarkRed
" Color:	darkgreen	#008000		2	DarkGreen
" Color:	darkyellow	#ca9d81		180	DarkYellow
" Color:	darkblue	#58678c		60	DarkBlue
" Color:	purple		#ad85cc		140	DarkMagenta
" Color:	darkcyan	#008080		6	DarkCyan
" Color:	lightgray	#caccd7		252	LightGray
" Color:	gray		#626870		242	DarkGray
" Color:	red		#ee6a6a		203	Red
" Color:	green		#54ca91		42	Green
" Color:	yellow		#f0c674		222	Yellow
" Color:	blue		#8599cc		103	Blue
" Color:	magenta		#ff00ff		13	Magenta
" Color:	cyan		#54c5ca		80	Cyan
" Color:	white		#d5d6d7		188	White
" Color:	foreground	#a2a8ad		248	LightGray
" Color:	gray2		#808080		8	DarkGray
" Color:	darkgray	#23242a		235	Black
" Color:	fold		#282d33		236	Black
" Color:	grayblue	#384048		238	Black
" Color:	search		#3b4d61		238	Black
" Color:	orange		#ff9800		208	Yellow
" Color:	aqua		#659ea2		73	DarkCyan
" Term Colors: background		darkred		darkgreen	darkyellow
" Term Colors: darkblue		purple		darkcyan	lightgray
" Term Colors: gray		red		green		yellow
" Term Colors: blue		magenta		cyan		white
" vim: et ts=2 sw=2
