" Name:         Pole
" Author:       https://github.com/Alvarocz/
" Maintainer:   Gianmaria Bajo <mg1979.git@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: lun 29 lug 2019 01:13:33 CEST

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'pole'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

if (has('termguicolors') && &termguicolors) || has('gui_running')
  hi Normal guifg=#a2a8ad guibg=#25262e guisp=NONE gui=NONE cterm=NONE
  call vsd#init('pole')
  hi Boolean guifg=#d5d6d7 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Builtin guifg=#ad85cc guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Character guifg=#ff9800 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#626870 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conditional guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#54c5ca guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#54c5ca guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#2c2d34 guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#2c2d34 guibg=#54c5ca guisp=NONE gui=NONE cterm=NONE
  hi Debug guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#008080 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Delimiter guifg=#626870 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#384048 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#25262e guibg=#ee6a6a guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ee6a6a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Exception guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#54ca91 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Function guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=fg guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#384048 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Import guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#ff00ff guibg=#2c2d34 guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#384048 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#008080 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MatchParen guifg=#f0c674 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Number guifg=#54ca91 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Operator guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PMenu guifg=#d5d6d7 guibg=#2c2d34 guisp=NONE gui=NONE cterm=NONE
  hi PMenuSbar guifg=NONE guibg=#2c2d34 guisp=NONE gui=NONE cterm=NONE
  hi PMenuSel guifg=#25262e guibg=#54ca91 guisp=NONE gui=NONE cterm=NONE
  hi PMenuThumb guifg=NONE guibg=#54ca91 guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#008080 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi PreProc guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#f0c674 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Repeat guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#54c5ca guibg=#384048 guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#f0c674 guibg=#2c2d34 guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#d5d6d7 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#626870 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#ee6a6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#25262e guibg=#626870 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#626870 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=fg guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Type guifg=#ad85cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#384048 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#808080 guibg=#384048 guisp=NONE gui=italic cterm=italic
  hi FoldColumn guifg=#58678c guibg=#23242a guisp=NONE gui=italic cterm=italic
  hi Conceal guifg=#808080 guibg=#23242a guisp=NONE gui=italic cterm=italic
  hi NonText guifg=#384048 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#808080 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterAdd guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ee6a6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignifySignAdd guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignifySignChange guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignifySignChangeDelete guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#ee6a6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#800000 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Identifier gui=NONE cterm=NONE
    hi Folded gui=NONE cterm=NONE
    hi FoldColumn gui=NONE cterm=NONE
    hi Conceal gui=NONE cterm=NONE
  endif
  hi DiffAdd    guifg=NONE guibg=#1E3C25 ctermfg=NONE ctermbg=23
  hi DiffChange guifg=NONE guibg=#1E1F51 ctermfg=NONE ctermbg=17
  hi DiffText   guifg=NONE guibg=#421F25 ctermfg=NONE ctermbg=52
  hi diffAdded guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffChanged guifg=#e89e70 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#ee6a6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffDiffer guifg=#e89e70 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi diffFile guifg=#ad85cc guibg=NONE guisp=NONE gui=bold cterm=bold
  hi diffLine guifg=#f0c674 guibg=NONE guisp=NONE gui=italic cterm=italic
  if !s:italics
    hi diffLine gui=NONE cterm=NONE
  endif
  if get(g:Vsd, 'extra_highlight', 1)
    hi pythonDecorator guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi pythonDecoratorName guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi pythonException guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi pythonExclass guifg=#54c5ca guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi htmlTag guifg=#626870 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi htmlTagName guifg=#ad85cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi htmlArg guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi cSpecial guifg=#008080 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi! link cBraces NonText
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=248 ctermbg=234 cterm=NONE
  if !has('patch-8.0.0616') " Fix for Vim bug
    set background=dark
  endif
  call vsd#init('pole')
  hi Boolean ctermfg=188 ctermbg=NONE cterm=bold
  hi Builtin ctermfg=140 ctermbg=NONE cterm=bold
  hi Character ctermfg=208 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=242 ctermbg=NONE cterm=italic
  hi Conditional ctermfg=188 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Constant ctermfg=80 ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=80 ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi Cursor ctermfg=236 ctermbg=80 cterm=NONE
  hi Debug ctermfg=222 ctermbg=NONE cterm=NONE
  hi Define ctermfg=6 ctermbg=NONE cterm=bold
  hi Delimiter ctermfg=242 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=NONE cterm=NONE
  hi Error ctermfg=234 ctermbg=203 cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=bold
  hi Exception ctermfg=103 ctermbg=NONE cterm=NONE
  hi Float ctermfg=42 ctermbg=NONE cterm=bold
  hi Function ctermfg=103 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=fg ctermbg=NONE cterm=italic
  hi Ignore ctermfg=238 ctermbg=NONE cterm=NONE
  hi Import ctermfg=188 ctermbg=NONE cterm=NONE
  hi Include ctermfg=188 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=13 ctermbg=236 cterm=NONE
  hi Keyword ctermfg=188 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=238 ctermbg=235 cterm=NONE
  hi Macro ctermfg=6 ctermbg=NONE cterm=bold
  hi MatchParen ctermfg=222 ctermbg=NONE cterm=bold
  hi Number ctermfg=42 ctermbg=NONE cterm=bold
  hi Operator ctermfg=60 ctermbg=NONE cterm=NONE
  hi PMenu ctermfg=188 ctermbg=236 cterm=NONE
  hi PMenuSbar ctermfg=NONE ctermbg=236 cterm=NONE
  hi PMenuSel ctermfg=234 ctermbg=42 cterm=NONE
  hi PMenuThumb ctermfg=NONE ctermbg=42 cterm=NONE
  hi PreCondit ctermfg=6 ctermbg=NONE cterm=bold
  hi PreProc ctermfg=103 ctermbg=NONE cterm=NONE
  hi Question ctermfg=222 ctermbg=NONE cterm=bold
  hi Repeat ctermfg=103 ctermbg=NONE cterm=NONE
  hi Search ctermfg=80 ctermbg=238 cterm=NONE
  hi Special ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=222 ctermbg=236 cterm=NONE
  hi Statement ctermfg=188 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=188 ctermbg=235 cterm=NONE
  hi StatusLineNC ctermfg=242 ctermbg=235 cterm=NONE
  hi StorageClass ctermfg=60 ctermbg=NONE cterm=NONE
  hi String ctermfg=203 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=103 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=234 ctermbg=242 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=242 cterm=NONE
  hi TabLineSel ctermfg=188 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=216 ctermbg=NONE cterm=NONE
  hi Title ctermfg=fg ctermbg=NONE cterm=bold
  hi Type ctermfg=140 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=60 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=NONE ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
  hi Folded ctermfg=8 ctermbg=238 cterm=italic
  hi FoldColumn ctermfg=60 ctermbg=235 cterm=italic
  hi Conceal ctermfg=8 ctermbg=235 cterm=italic
  hi NonText ctermfg=238 ctermbg=NONE cterm=NONE
  hi Label ctermfg=60 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=8 ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=42 ctermbg=NONE cterm=NONE
  hi GitGutterChange ctermfg=216 ctermbg=NONE cterm=NONE
  hi GitGutterChangeDelete ctermfg=216 ctermbg=NONE cterm=NONE
  hi GitGutterDelete ctermfg=203 ctermbg=NONE cterm=NONE
  hi SignifySignAdd ctermfg=42 ctermbg=NONE cterm=NONE
  hi SignifySignChange ctermfg=216 ctermbg=NONE cterm=NONE
  hi SignifySignChangeDelete ctermfg=216 ctermbg=NONE cterm=NONE
  hi SignifySignDelete ctermfg=203 ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=1 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi Identifier cterm=NONE
    hi Folded cterm=NONE
    hi FoldColumn cterm=NONE
    hi Conceal cterm=NONE
  endif
  hi DiffAdd    guifg=NONE guibg=#1E3C25 ctermfg=NONE ctermbg=23
  hi DiffChange guifg=NONE guibg=#1E1F51 ctermfg=NONE ctermbg=17
  hi DiffText   guifg=NONE guibg=#421F25 ctermfg=NONE ctermbg=52
  hi diffAdded ctermfg=42 ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=216 ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=203 ctermbg=NONE cterm=NONE
  hi diffDiffer ctermfg=216 ctermbg=NONE cterm=bold
  hi diffFile ctermfg=140 ctermbg=NONE cterm=bold
  hi diffLine ctermfg=222 ctermbg=NONE cterm=italic
  if !s:italics
    hi diffLine cterm=NONE
  endif
  if get(g:Vsd, 'extra_highlight', 1)
    hi pythonDecorator ctermfg=42 ctermbg=NONE cterm=NONE
    hi pythonDecoratorName ctermfg=42 ctermbg=NONE cterm=NONE
    hi pythonException ctermfg=60 ctermbg=NONE cterm=NONE
    hi pythonExclass ctermfg=80 ctermbg=NONE cterm=NONE
    hi htmlTag ctermfg=242 ctermbg=NONE cterm=NONE
    hi htmlTagName ctermfg=140 ctermbg=NONE cterm=NONE
    hi htmlArg ctermfg=188 ctermbg=NONE cterm=NONE
    hi cSpecial ctermfg=6 ctermbg=NONE cterm=NONE
    hi! link cBraces NonText
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color:	background	#25262e		234	Black
" Color:	darkred		#800000		1	DarkRed
" Color:	darkgreen	#008000		2	DarkGreen
" Color:	darkyellow	#e89e70		216	DarkYellow
" Color:	darkblue	#58678c		60	DarkBlue
" Color:	purple		#ad85cc		140	DarkMagenta
" Color:	darkcyan	#008080		6	DarkCyan
" Color:	lightgray	#caccd7		252	LightGray
" Color:	gray		#626870		242	DarkGray
" Color:	red		#ee6a6a		203	Red
" Color:	green		#54ca91		42	Green
" Color:	yellow		#f0c674		222	Yellow
" Color:	blue		#8599cc		103	Blue
" Color:	magenta		#ff00ff		13	Magenta
" Color:	cyan		#54c5ca		80	Cyan
" Color:	white		#d5d6d7		188	White
" Color:	foreground	#a2a8ad		248	LightGray
" Color:	gray2		#808080		8	DarkGray
" Color:	darkgray	#2c2d34		236	Black
" Color:	grayblue	#23242a		235	Black
" Color:	grayblue2	#384048		238	Black
" Color:	orange		#ff9800		208	Black
" vim: et ts=2 sw=2
