" Name:         Pole
" Author:       https://github.com/Alvarocz/
" Maintainer:   Gianmaria Bajo <mg1979.git@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: Fri 14 Feb 2020 08:14:33 PM STD

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'pole'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#25262e', '#800000', '#008000', '#ca9d81',
        \ '#58678c', '#ad85cc', '#008080', '#caccd7', '#626870', '#ee6a6a',
        \ '#54ca91', '#f0c674', '#8599cc', '#ff00ff', '#54c5ca', '#d5d6d7']
  if has('nvim')
    let g:terminal_color_0 = '#25262e'
    let g:terminal_color_1 = '#800000'
    let g:terminal_color_2 = '#008000'
    let g:terminal_color_3 = '#ca9d81'
    let g:terminal_color_4 = '#58678c'
    let g:terminal_color_5 = '#ad85cc'
    let g:terminal_color_6 = '#008080'
    let g:terminal_color_7 = '#caccd7'
    let g:terminal_color_8 = '#626870'
    let g:terminal_color_9 = '#ee6a6a'
    let g:terminal_color_10 = '#54ca91'
    let g:terminal_color_11 = '#f0c674'
    let g:terminal_color_12 = '#8599cc'
    let g:terminal_color_13 = '#ff00ff'
    let g:terminal_color_14 = '#54c5ca'
    let g:terminal_color_15 = '#d5d6d7'
  endif
  hi Normal guifg=#a2a8ad guibg=#25262e guisp=NONE gui=NONE cterm=NONE
  call vsd#init('pole')
  hi Boolean guifg=#d5d6d7 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Builtin guifg=#ad85cc guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Character guifg=#ff9800 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#626870 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conditional guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#ff9800 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#54c5ca guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=#58678c guisp=NONE gui=NONE cterm=NONE
  hi Debug guifg=#f0c674 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#008080 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Delimiter guifg=#626870 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#384048 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#25262e guibg=#ee6a6a guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ee6a6a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Exception guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#54ca91 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Function guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#659ea2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#384048 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Import guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#ff00ff guibg=#384048 guisp=NONE gui=bold cterm=bold
  hi Keyword guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#384048 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#008080 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MatchParen guifg=#f0c674 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Number guifg=#54ca91 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Operator guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PMenu guifg=#d5d6d7 guibg=#384048 guisp=NONE gui=NONE cterm=NONE
  hi PMenuSbar guifg=NONE guibg=#384048 guisp=NONE gui=NONE cterm=NONE
  hi PMenuSel guifg=#25262e guibg=#54ca91 guisp=NONE gui=NONE cterm=NONE
  hi PMenuThumb guifg=NONE guibg=#54ca91 guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#008080 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi PreProc guifg=#008080 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Question guifg=#f0c674 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Repeat guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#54c5ca guibg=#3b4d61 guisp=NONE gui=bold cterm=bold
  hi Special guifg=#ca9d81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#ca9d81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#ca9d81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#f0c674 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#d5d6d7 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#626870 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#ee6a6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#8599cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#25262e guibg=#626870 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#626870 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#ca9d81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#d5d6d7 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Type guifg=#ad85cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#384048 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#23242a guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#384048 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#808080 guibg=#282d33 guisp=NONE gui=italic cterm=italic
  hi FoldColumn guifg=#58678c guibg=#23242a guisp=NONE gui=italic cterm=italic
  hi Conceal guifg=#808080 guibg=#23242a guisp=NONE gui=italic cterm=italic
  hi NonText guifg=#384048 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#f0c674 guibg=#58678c guisp=NONE gui=bold cterm=bold
  hi SpellBad guifg=#ee6a6a guibg=NONE guisp=NONE gui=undercurl cterm=undercurl
  hi SpellCap guifg=#54ca91 guibg=NONE guisp=NONE gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#8599cc guibg=NONE guisp=NONE gui=undercurl cterm=undercurl
  hi SpellRare guifg=#ad85cc guibg=NONE guisp=NONE gui=undercurl cterm=undercurl
  hi DiffDelete guifg=#800000 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Folded gui=NONE cterm=NONE
    hi FoldColumn gui=NONE cterm=NONE
    hi Conceal gui=NONE cterm=NONE
  endif
  hi DiffAdd    guifg=NONE guibg=#1E3C25 ctermfg=NONE ctermbg=23
  hi DiffChange guifg=NONE guibg=#1E1F51 ctermfg=NONE ctermbg=17
  hi DiffText   guifg=NONE guibg=#421F25 ctermfg=NONE ctermbg=52
  hi diffAdded guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffChanged guifg=#ca9d81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#ee6a6a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffDiffer guifg=#ca9d81 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi diffFile guifg=#ad85cc guibg=NONE guisp=NONE gui=bold cterm=bold
  hi diffLine guifg=#f0c674 guibg=NONE guisp=NONE gui=italic cterm=italic
  if !s:italics
    hi diffLine gui=NONE cterm=NONE
  endif
  if get(g:Vsd, 'extra_highlight', 1)
    hi GitGutterAdd guifg=#54ca91 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi GitGutterChange guifg=#ca9d81 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi GitGutterChangeDelete guifg=#ca9d81 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi GitGutterDelete guifg=#ee6a6a guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi SignifySignAdd guifg=#54ca91 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi SignifySignChange guifg=#ca9d81 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi SignifySignChangeDelete guifg=#ca9d81 guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi SignifySignDelete guifg=#ee6a6a guibg=#23242a guisp=NONE gui=NONE cterm=NONE
    hi pythonDecorator guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi pythonDecoratorName guifg=#54ca91 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi pythonException guifg=#58678c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi pythonExclass guifg=#54c5ca guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi htmlTag guifg=#626870 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi htmlTagName guifg=#ad85cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi htmlArg guifg=#d5d6d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi cSpecial guifg=#008080 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi! link cBraces Delimiter
    hi! link vimMapMod Special
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=248 ctermbg=234 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  call vsd#init('pole')
  hi Boolean ctermfg=188 ctermbg=NONE cterm=bold
  hi Builtin ctermfg=140 ctermbg=NONE cterm=bold
  hi Character ctermfg=208 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=242 ctermbg=NONE cterm=italic
  hi Conditional ctermfg=188 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Constant ctermfg=208 ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=80 ctermbg=235 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=60 cterm=NONE
  hi Debug ctermfg=222 ctermbg=NONE cterm=NONE
  hi Define ctermfg=6 ctermbg=NONE cterm=bold
  hi Delimiter ctermfg=242 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=NONE cterm=NONE
  hi Error ctermfg=234 ctermbg=203 cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=bold
  hi Exception ctermfg=103 ctermbg=NONE cterm=NONE
  hi Float ctermfg=42 ctermbg=NONE cterm=bold
  hi Function ctermfg=103 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=73 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=238 ctermbg=NONE cterm=NONE
  hi Import ctermfg=188 ctermbg=NONE cterm=NONE
  hi Include ctermfg=188 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=13 ctermbg=238 cterm=bold
  hi Keyword ctermfg=188 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=238 ctermbg=235 cterm=NONE
  hi Macro ctermfg=6 ctermbg=NONE cterm=bold
  hi MatchParen ctermfg=222 ctermbg=NONE cterm=bold
  hi Number ctermfg=42 ctermbg=NONE cterm=bold
  hi Operator ctermfg=60 ctermbg=NONE cterm=NONE
  hi PMenu ctermfg=188 ctermbg=238 cterm=NONE
  hi PMenuSbar ctermfg=NONE ctermbg=238 cterm=NONE
  hi PMenuSel ctermfg=234 ctermbg=42 cterm=NONE
  hi PMenuThumb ctermfg=NONE ctermbg=42 cterm=NONE
  hi PreCondit ctermfg=6 ctermbg=NONE cterm=bold
  hi PreProc ctermfg=6 ctermbg=NONE cterm=bold
  hi Question ctermfg=222 ctermbg=NONE cterm=bold
  hi Repeat ctermfg=103 ctermbg=NONE cterm=NONE
  hi Search ctermfg=80 ctermbg=238 cterm=bold
  hi Special ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=216 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=222 ctermbg=235 cterm=NONE
  hi Statement ctermfg=188 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=188 ctermbg=235 cterm=NONE
  hi StatusLineNC ctermfg=242 ctermbg=235 cterm=NONE
  hi StorageClass ctermfg=60 ctermbg=NONE cterm=NONE
  hi String ctermfg=203 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=103 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=234 ctermbg=242 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=242 cterm=NONE
  hi TabLineSel ctermfg=188 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=216 ctermbg=NONE cterm=NONE
  hi Title ctermfg=188 ctermbg=NONE cterm=bold
  hi Type ctermfg=140 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=60 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=238 ctermbg=235 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
  hi Folded ctermfg=8 ctermbg=238 cterm=italic
  hi FoldColumn ctermfg=60 ctermbg=235 cterm=italic
  hi Conceal ctermfg=8 ctermbg=235 cterm=italic
  hi NonText ctermfg=238 ctermbg=NONE cterm=NONE
  hi Label ctermfg=60 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=222 ctermbg=60 cterm=bold
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=42 ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=103 ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=140 ctermbg=NONE cterm=undercurl
  hi DiffDelete ctermfg=1 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi Folded cterm=NONE
    hi FoldColumn cterm=NONE
    hi Conceal cterm=NONE
  endif
  hi DiffAdd    guifg=NONE guibg=#1E3C25 ctermfg=NONE ctermbg=23
  hi DiffChange guifg=NONE guibg=#1E1F51 ctermfg=NONE ctermbg=17
  hi DiffText   guifg=NONE guibg=#421F25 ctermfg=NONE ctermbg=52
  hi diffAdded ctermfg=42 ctermbg=NONE cterm=NONE
  hi diffChanged ctermfg=216 ctermbg=NONE cterm=NONE
  hi diffRemoved ctermfg=203 ctermbg=NONE cterm=NONE
  hi diffDiffer ctermfg=216 ctermbg=NONE cterm=bold
  hi diffFile ctermfg=140 ctermbg=NONE cterm=bold
  hi diffLine ctermfg=222 ctermbg=NONE cterm=italic
  if !s:italics
    hi diffLine cterm=NONE
  endif
  if get(g:Vsd, 'extra_highlight', 1)
    hi GitGutterAdd ctermfg=42 ctermbg=235 cterm=NONE
    hi GitGutterChange ctermfg=216 ctermbg=235 cterm=NONE
    hi GitGutterChangeDelete ctermfg=216 ctermbg=235 cterm=NONE
    hi GitGutterDelete ctermfg=203 ctermbg=235 cterm=NONE
    hi SignifySignAdd ctermfg=42 ctermbg=235 cterm=NONE
    hi SignifySignChange ctermfg=216 ctermbg=235 cterm=NONE
    hi SignifySignChangeDelete ctermfg=216 ctermbg=235 cterm=NONE
    hi SignifySignDelete ctermfg=203 ctermbg=235 cterm=NONE
    hi pythonDecorator ctermfg=42 ctermbg=NONE cterm=NONE
    hi pythonDecoratorName ctermfg=42 ctermbg=NONE cterm=NONE
    hi pythonException ctermfg=60 ctermbg=NONE cterm=NONE
    hi pythonExclass ctermfg=80 ctermbg=NONE cterm=NONE
    hi htmlTag ctermfg=242 ctermbg=NONE cterm=NONE
    hi htmlTagName ctermfg=140 ctermbg=NONE cterm=NONE
    hi htmlArg ctermfg=188 ctermbg=NONE cterm=NONE
    hi cSpecial ctermfg=6 ctermbg=NONE cterm=NONE
    hi! link cBraces Delimiter
    hi! link vimMapMod Special
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color:	background	#25262e		234	Black
" Color:	darkred		#800000		1	DarkRed
" Color:	darkgreen	#008000		2	DarkGreen
" Color:	darkyellow	#ca9d81		216	DarkYellow
" Color:	darkblue	#58678c		60	DarkBlue
" Color:	purple		#ad85cc		140	DarkMagenta
" Color:	darkcyan	#008080		6	DarkCyan
" Color:	lightgray	#caccd7		252	LightGray
" Color:	gray		#626870		242	DarkGray
" Color:	red		#ee6a6a		203	Red
" Color:	green		#54ca91		42	Green
" Color:	yellow		#f0c674		222	Yellow
" Color:	blue		#8599cc		103	Blue
" Color:	magenta		#ff00ff		13	Magenta
" Color:	cyan		#54c5ca		80	Cyan
" Color:	white		#d5d6d7		188	White
" Color:	foreground	#a2a8ad		248	LightGray
" Color:	gray2		#808080		8	DarkGray
" Color:	darkgray	#23242a		235	Black
" Color:	fold	 	#282d33		238	Black
" Color:	grayblue	#384048		238	Black
" Color:	search		#3b4d61		238	Black
" Color:	orange		#ff9800		208	Yellow
" Color:	aqua		#659ea2		73	DarkCyan
" Term Colors: background		darkred		darkgreen	darkyellow
" Term Colors: darkblue		purple		darkcyan	lightgray
" Term Colors: gray		red		green		yellow
" Term Colors: blue		magenta		cyan		white
" vim: et ts=2 sw=2
