" Name:         Vim Studio Dark
" Author:       Gianmaria Bajo <mg1979.git@gmail.com>
" Maintainer:   Gianmaria Bajo <mg1979.git@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: sab 27 mar 2021 23:06:38 CET

" Generated by Colortemplate v2.1.0

hi clear
let g:colors_name = 'vsdark'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#4c4e50', '#df8c8c', '#a8ce93', '#dada93', '#83afe5', '#9a93e1', '#83afe5', '#c9c6c9', '#608b4e', '#f2c38f', '#a8ce93', '#dada93', '#83afe5', '#c586c0', '#83afe5', '#c0d0d0']
    if has('nvim')
      let g:terminal_color_0 = '#4c4e50'
      let g:terminal_color_1 = '#df8c8c'
      let g:terminal_color_2 = '#a8ce93'
      let g:terminal_color_3 = '#dada93'
      let g:terminal_color_4 = '#83afe5'
      let g:terminal_color_5 = '#9a93e1'
      let g:terminal_color_6 = '#83afe5'
      let g:terminal_color_7 = '#c9c6c9'
      let g:terminal_color_8 = '#608b4e'
      let g:terminal_color_9 = '#f2c38f'
      let g:terminal_color_10 = '#a8ce93'
      let g:terminal_color_11 = '#dada93'
      let g:terminal_color_12 = '#83afe5'
      let g:terminal_color_13 = '#c586c0'
      let g:terminal_color_14 = '#83afe5'
      let g:terminal_color_15 = '#c0d0d0'
    endif
    hi Normal guifg=#c0d0d0 guibg=#1e1e1e gui=NONE cterm=NONE
    let g:Vsd = get(g:, 'Vsd', {})
    silent! call vsd#init('vsdark')
    hi MatchParen guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#83afe5 guibg=NONE gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=#204366 gui=NONE cterm=NONE
    hi VisualNOS guifg=NONE guibg=#204366 gui=NONE cterm=NONE
    hi Folded guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#569cd6 guibg=#212733 gui=NONE cterm=NONE
    hi VertSplit guifg=#333233 guibg=#212733 gui=NONE cterm=NONE
    hi IncSearch guifg=#333233 guibg=#df8c8c gui=NONE cterm=NONE
    hi Search guifg=#333233 guibg=#a8ce93 gui=NONE cterm=NONE
    hi Question guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
    hi ModeMsg guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
    hi WildMenu guifg=fg guibg=#073655 gui=NONE cterm=NONE
    hi StatusLine guifg=fg guibg=#4c4e50 gui=NONE cterm=NONE
    hi StatusLineTerm guifg=fg guibg=#4c4e50 gui=NONE cterm=NONE
    hi StatusLineNC guifg=fg guibg=NONE gui=NONE cterm=NONE
    hi StatusLineTermNC guifg=fg guibg=NONE gui=NONE cterm=NONE
    hi Error guifg=#c0d0d0 guibg=#730b00 gui=NONE cterm=NONE
    hi ErrorMsg guifg=#c0d0d0 guibg=#730b00 gui=NONE cterm=NONE
    hi WarningMsg guifg=#df8c8c guibg=NONE gui=NONE cterm=NONE
    hi Todo guifg=#df8c8c guibg=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=#ff0000 guibg=NONE gui=undercurl cterm=undercurl
    hi SpellCap guifg=#df8c8c guibg=NONE gui=undercurl cterm=undercurl
    hi SpellLocal guifg=#569cd6 guibg=NONE gui=undercurl cterm=undercurl
    hi SpellRare guifg=#df8c8c guibg=NONE gui=undercurl cterm=undercurl
    hi Pmenu guifg=fg guibg=#4c4e50 gui=NONE cterm=NONE
    hi PmenuSel guifg=fg guibg=#073655 gui=NONE cterm=NONE
    hi PmenuSbar guifg=#608b4e guibg=#608b4e gui=NONE cterm=NONE
    hi PmenuThumb guifg=#569cd6 guibg=#569cd6 gui=NONE cterm=NONE
    hi DiffAdd guifg=NONE guibg=#073655 gui=NONE cterm=NONE
    hi DiffChange guifg=NONE guibg=#333233 gui=NONE cterm=NONE
    hi DiffDelete guifg=#ff0000 guibg=NONE gui=bold cterm=bold
    hi DiffText guifg=NONE guibg=#730b00 gui=bold cterm=bold
    hi diffDiffer guifg=#f2c38f guibg=NONE gui=bold cterm=bold
    hi diffFile guifg=#ce9178 guibg=NONE gui=bold cterm=bold
    hi diffLine guifg=#dada93 guibg=NONE gui=italic cterm=italic
    if !s:italics
      hi diffLine gui=NONE cterm=NONE
    endif
    hi diffAdded guifg=#a8ce93 guibg=#2a3324 ctermfg=150 ctermbg=236 gui=none cterm=none
    hi diffChanged guifg=#f2c38f guibg=#33291e ctermfg=223 ctermbg=235 gui=none cterm=none
    hi diffRemoved guifg=#df8c8c guibg=#332020 ctermfg=174 ctermbg=235 gui=none cterm=none
    hi SignColumn guifg=fg guibg=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#4c4e50 guibg=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#333233 gui=NONE cterm=NONE
    hi CursorColumn guifg=fg guibg=#333233 gui=NONE cterm=NONE
    hi ColorColumn guifg=fg guibg=#333233 gui=NONE cterm=NONE
    hi EndOfBuffer guifg=#4c4e50 guibg=NONE gui=NONE cterm=NONE
    hi TabLine guifg=#a9a9a9 guibg=#333233 gui=NONE cterm=NONE
    hi TabLineSel guifg=#569cd6 guibg=#4c4e50 gui=NONE cterm=NONE
    hi TabLineFill guifg=#a9a9a9 guibg=#333233 gui=NONE cterm=NONE
    hi ToolbarLine guifg=fg guibg=#4c4e50 gui=NONE cterm=NONE
    hi ToolbarButton guifg=#4c4e50 guibg=#83afe5 gui=NONE cterm=NONE
    hi Directory guifg=#42dcd7 guibg=NONE gui=NONE cterm=NONE
    hi Constant guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
    hi String guifg=#ce9178 guibg=NONE gui=NONE cterm=NONE
    hi Number guifg=#a8ce93 guibg=NONE gui=NONE cterm=NONE
    hi Identifier guifg=#7fc1ca guibg=NONE gui=NONE cterm=NONE
    hi Function guifg=#dada93 guibg=NONE gui=NONE cterm=NONE
    hi Statement guifg=#c586c0 guibg=NONE gui=NONE cterm=NONE
    hi! link Conditional Statement
    hi! link Keyword Statement
    hi Operator guifg=#a9a9a9 guibg=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#9a93e1 guibg=NONE gui=NONE cterm=NONE
    hi! link Include PreProc
    hi! link Define PreProc
    hi! link Macro PreProc
    hi! link PreCondit PreProc
    hi Type guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
    hi Underlined guifg=#c586c0 guibg=NONE gui=underline cterm=underline
    hi Special guifg=#607b9e guibg=NONE gui=NONE cterm=NONE
    hi NonText guifg=#4c4e50 guibg=NONE gui=NONE cterm=NONE
    hi Title guifg=#f2c38f guibg=NONE gui=NONE cterm=NONE
    hi Comment guifg=#608b4e guibg=NONE gui=NONE cterm=NONE
    hi Ignore guifg=#4c4e50 guibg=NONE gui=NONE cterm=NONE
    hi Conceal guifg=#608b4e guibg=NONE gui=NONE cterm=NONE
    hi Cursor guifg=#1e1e1e guibg=#00af00 gui=NONE cterm=NONE
    hi Command guifg=#c586c0 guibg=NONE gui=NONE cterm=NONE
    hi! link QuickFixLine Search
    hi! link Delimiter Special
    hi GitGutterAdd guifg=#00af00 guibg=NONE gui=NONE cterm=NONE
    hi GitGutterChange guifg=#f2c38f guibg=NONE gui=NONE cterm=NONE
    hi GitGutterChangeDelete guifg=#f2c38f guibg=NONE gui=NONE cterm=NONE
    hi GitGutterDelete guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
    hi SignifySignAdd guifg=#00af00 guibg=NONE gui=NONE cterm=NONE
    hi SignifySignChange guifg=#f2c38f guibg=NONE gui=NONE cterm=NONE
    hi SignifySignChangeDelete guifg=#f2c38f guibg=NONE gui=NONE cterm=NONE
    hi SignifySignDelete guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
    if get(g:Vsd, 'extra_highlight', 1)
      hi! link helpCommand Comment
      hi! link helpSectionDelim Folded
      hi! link helpHeader PreProc
      hi! link helpHeadline Statement
      hi! link helpHyperTextEntry String
      hi! link helpHyperTextJump Identifier
      hi! link helpExample Comment
      hi! link helpOption Type
      hi! link helpSpecial Special
      hi pythonBytesEscape guifg=#ff5947 guibg=NONE gui=NONE cterm=NONE
      hi pythonStrFormat guifg=#ff5947 guibg=NONE gui=NONE cterm=NONE
      hi pythonStrFormatting guifg=#ff5947 guibg=NONE gui=NONE cterm=NONE
      hi! link pythonOperator Statement
      hi cSpecial guifg=#ff5947 guibg=NONE gui=NONE cterm=NONE
      hi! link cBraces Delimiter
    endif
    let g:fzf_colors = { "fg": ["fg", "Normal"], "bg": ["bg", "Normal"], "hl": ["fg", "Conditional"], "fg+": ["fg", "CursorLine", "CursorColumn", "Normal"], "bg+": ["bg", "CursorLine", "CursorColumn"], "hl+": ["fg", "Conditional"], "info": ["fg", "Conditional"], "border": ["fg", "Ignore"], "prompt": ["fg", "Comment"], "pointer": ["fg", "Conditional"], "marker": ["fg", "Conditional"], "spinner": ["fg", "Conditional"], "header": ["fg", "Conditional"] }
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#1e1e1e', '#a31515', '#003f00', '#811f3f', '#000080', '#af00db', '#007acc', '#f3f3f3', '#606060', '#ff0000', '#008000', '#f8c9ab', '#0000ff', '#af00db', '#007acc', '#ffffff']
  if has('nvim')
    let g:terminal_color_0 = '#1e1e1e'
    let g:terminal_color_1 = '#a31515'
    let g:terminal_color_2 = '#003f00'
    let g:terminal_color_3 = '#811f3f'
    let g:terminal_color_4 = '#000080'
    let g:terminal_color_5 = '#af00db'
    let g:terminal_color_6 = '#007acc'
    let g:terminal_color_7 = '#f3f3f3'
    let g:terminal_color_8 = '#606060'
    let g:terminal_color_9 = '#ff0000'
    let g:terminal_color_10 = '#008000'
    let g:terminal_color_11 = '#f8c9ab'
    let g:terminal_color_12 = '#0000ff'
    let g:terminal_color_13 = '#af00db'
    let g:terminal_color_14 = '#007acc'
    let g:terminal_color_15 = '#ffffff'
  endif
  hi Normal guifg=#1e1e1e guibg=#ffffff gui=NONE cterm=NONE
  let g:Vsd = get(g:, 'Vsd', {})
  silent! call vsd#init('vslight')
  hi MatchParen guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#0000ff guibg=#f3f3f3 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#add6ff gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#f3f3f3 gui=NONE cterm=NONE
  hi Folded guifg=#606060 guibg=#f3f3f3 gui=NONE cterm=NONE
  hi FoldColumn guifg=#606060 guibg=#f3f3f3 gui=NONE cterm=NONE
  hi IncSearch guifg=#811f3f guibg=#f8c9ab gui=bold cterm=bold
  hi Search guifg=NONE guibg=#f8c9ab gui=NONE cterm=NONE
  hi Question guifg=#0000ff guibg=#f8c9ab gui=NONE cterm=NONE
  hi MoreMsg guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#007acc guibg=#f3f3f3 gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#007acc guibg=#f3f3f3 gui=NONE cterm=NONE
  hi StatusLineNC guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi StatusLineTermNC guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#ff0000 guibg=NONE gui=undercurl cterm=undercurl
  hi SpellCap guifg=#af00db guibg=NONE gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#007acc guibg=NONE gui=undercurl cterm=undercurl
  hi SpellRare guifg=#af00db guibg=NONE gui=undercurl cterm=undercurl
  hi Pmenu guifg=#333333 guibg=#cecece gui=NONE cterm=NONE
  hi PmenuSel guifg=#cecece guibg=#007acc gui=NONE cterm=NONE
  hi PmenuThumb guifg=#0000ff guibg=#0000ff gui=NONE cterm=NONE
  hi PmenuSbar guifg=#003f00 guibg=#003f00 gui=NONE cterm=NONE
  hi! link WildMenu PmenuSel
  hi DiffAdd guifg=NONE guibg=#add6ff gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#f3f3f3 gui=NONE cterm=NONE
  hi DiffDelete guifg=#ff0000 guibg=NONE gui=bold cterm=bold
  hi DiffText guifg=NONE guibg=#f2c38f gui=bold cterm=bold
  hi diffFile guifg=#a31515 guibg=NONE gui=bold cterm=bold
  hi diffLine guifg=#811f3f guibg=NONE gui=italic cterm=italic
  if !s:italics
    hi diffLine gui=NONE cterm=NONE
  endif
  hi diffAdded guifg=#003f00 guibg=#afdfff ctermfg=22 ctermbg=153 gui=none cterm=none
  hi diffChanged guifg=#682900 guibg=#c0c0c0 ctermfg=88 ctermbg=7 gui=none cterm=none
  hi diffRemoved guifg=#a31515 guibg=#afafdf ctermfg=124 ctermbg=146 gui=none cterm=none
  hi SignColumn guifg=NONE guibg=#f3f3f3 gui=NONE cterm=NONE
  hi LineNr guifg=#606060 guibg=#f3f3f3 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#f3f3f3 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#f3f3f3 gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#f3f3f3 gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#606060 guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#606060 guibg=#f3f3f3 gui=NONE cterm=NONE
  hi TabLine guifg=fg guibg=#f3f3f3 gui=NONE cterm=NONE
  hi TabLineSel guifg=#f3f3f3 guibg=#0000ff gui=NONE cterm=NONE
  hi TabLineFill guifg=fg guibg=#f3f3f3 gui=NONE cterm=NONE
  hi ToolbarLine guifg=#f3f3f3 guibg=#0000ff gui=NONE cterm=NONE
  hi ToolbarButton guifg=#0000ff guibg=#f3f3f3 gui=NONE cterm=NONE
  hi Constant guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#a31515 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=fg guibg=NONE gui=bold cterm=bold
  hi Directory guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#333333 guibg=NONE gui=bold cterm=bold
  hi Function guifg=#795e26 guibg=NONE gui=bold cterm=bold
  hi Statement guifg=#af00db guibg=NONE gui=NONE cterm=NONE
  hi! link Conditional Statement
  hi! link Repeat Statement
  hi! link Exception Statement
  hi Operator guifg=#333333 guibg=NONE gui=NONE cterm=NONE
  hi! link Keyword Statement
  hi PreProc guifg=#af00db guibg=NONE gui=NONE cterm=NONE
  hi! link Include PreProc
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi Type guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#af00db guibg=NONE gui=underline cterm=underline
  hi Special guifg=#811f3f guibg=NONE gui=NONE cterm=NONE
  hi! link SpecialKey Special
  hi Delimiter guifg=#606060 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#606060 guibg=NONE gui=NONE cterm=NONE
  hi Title guifg=#007acc guibg=NONE gui=NONE cterm=NONE
  hi Comment guifg=#008000 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#606060 guibg=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#003f00 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#f3f3f3 guibg=#0000ff gui=NONE cterm=NONE
  hi Command guifg=#af00db guibg=NONE gui=NONE cterm=NONE
  hi! link QuickFixLine Search
  hi GitGutterAdd guifg=#003f00 guibg=#f3f3f3 gui=NONE cterm=NONE
  hi GitGutterChange guifg=#811f3f guibg=#f3f3f3 gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#811f3f guibg=#f3f3f3 gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ff0000 guibg=#f3f3f3 gui=NONE cterm=NONE
  hi SignifySignAdd guifg=#003f00 guibg=#f3f3f3 gui=NONE cterm=NONE
  hi SignifySignChange guifg=#811f3f guibg=#f3f3f3 gui=NONE cterm=NONE
  hi SignifySignChangeDelete guifg=#811f3f guibg=#f3f3f3 gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#ff0000 guibg=#f3f3f3 gui=NONE cterm=NONE
  if get(g:Vsd, 'extra_highlight', 1)
    hi! link helpCommand Type
    hi! link helpSectionDelim PreProc
    hi! link HelpHeadline Statement
    hi! link helpHyperTextEntry String
    hi! link HelpHeadline String
    hi pythonBytesEscape guifg=#811f3f guibg=NONE gui=NONE cterm=NONE
    hi pythonStrFormat guifg=#811f3f guibg=NONE gui=NONE cterm=NONE
    hi pythonStrFormatting guifg=#811f3f guibg=NONE gui=NONE cterm=NONE
    hi! link pythonOperator Statement
    hi cSpecial guifg=#811f3f guibg=NONE gui=NONE cterm=NONE
    hi! link cBraces Delimiter
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Normal ctermfg=252 ctermbg=234 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    let g:Vsd = get(g:, 'Vsd', {})
    silent! call vsd#init('vsdark')
    hi MatchParen ctermfg=196 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=110 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=19 cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=19 cterm=NONE
    hi Folded ctermfg=39 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=39 ctermbg=235 cterm=NONE
    hi VertSplit ctermfg=236 ctermbg=235 cterm=NONE
    hi IncSearch ctermfg=236 ctermbg=174 cterm=NONE
    hi Search ctermfg=236 ctermbg=150 cterm=NONE
    hi Question ctermfg=39 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=39 ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=39 ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=fg ctermbg=17 cterm=NONE
    hi StatusLine ctermfg=fg ctermbg=239 cterm=NONE
    hi StatusLineTerm ctermfg=fg ctermbg=239 cterm=NONE
    hi StatusLineNC ctermfg=fg ctermbg=NONE cterm=NONE
    hi StatusLineTermNC ctermfg=fg ctermbg=NONE cterm=NONE
    hi Error ctermfg=252 ctermbg=88 cterm=NONE
    hi ErrorMsg ctermfg=252 ctermbg=88 cterm=NONE
    hi WarningMsg ctermfg=174 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=174 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=196 ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=174 ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=39 ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=174 ctermbg=NONE cterm=undercurl
    hi Pmenu ctermfg=fg ctermbg=239 cterm=NONE
    hi PmenuSel ctermfg=fg ctermbg=17 cterm=NONE
    hi PmenuSbar ctermfg=65 ctermbg=65 cterm=NONE
    hi PmenuThumb ctermfg=39 ctermbg=39 cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=17 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=236 cterm=NONE
    hi DiffDelete ctermfg=196 ctermbg=NONE cterm=bold
    hi DiffText ctermfg=NONE ctermbg=88 cterm=bold
    hi diffDiffer ctermfg=223 ctermbg=NONE cterm=bold
    hi diffFile ctermfg=173 ctermbg=NONE cterm=bold
    hi diffLine ctermfg=186 ctermbg=NONE cterm=italic
    if !s:italics
      hi diffLine cterm=NONE
    endif
    hi diffAdded guifg=#a8ce93 guibg=#2a3324 ctermfg=150 ctermbg=236 gui=none cterm=none
    hi diffChanged guifg=#f2c38f guibg=#33291e ctermfg=223 ctermbg=235 gui=none cterm=none
    hi diffRemoved guifg=#df8c8c guibg=#332020 ctermfg=174 ctermbg=235 gui=none cterm=none
    hi SignColumn ctermfg=fg ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=239 ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorColumn ctermfg=fg ctermbg=236 cterm=NONE
    hi ColorColumn ctermfg=fg ctermbg=236 cterm=NONE
    hi EndOfBuffer ctermfg=239 ctermbg=NONE cterm=NONE
    hi TabLine ctermfg=248 ctermbg=236 cterm=NONE
    hi TabLineSel ctermfg=39 ctermbg=239 cterm=NONE
    hi TabLineFill ctermfg=248 ctermbg=236 cterm=NONE
    hi ToolbarLine ctermfg=fg ctermbg=239 cterm=NONE
    hi ToolbarButton ctermfg=239 ctermbg=110 cterm=NONE
    hi Directory ctermfg=44 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=39 ctermbg=NONE cterm=NONE
    hi String ctermfg=173 ctermbg=NONE cterm=NONE
    hi Number ctermfg=150 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=109 ctermbg=NONE cterm=NONE
    hi Function ctermfg=186 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=176 ctermbg=NONE cterm=NONE
    hi! link Conditional Statement
    hi! link Keyword Statement
    hi Operator ctermfg=248 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=104 ctermbg=NONE cterm=NONE
    hi! link Include PreProc
    hi! link Define PreProc
    hi! link Macro PreProc
    hi! link PreCondit PreProc
    hi Type ctermfg=39 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=176 ctermbg=NONE cterm=underline
    hi Special ctermfg=67 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=239 ctermbg=NONE cterm=NONE
    hi Title ctermfg=223 ctermbg=NONE cterm=NONE
    hi Comment ctermfg=65 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=239 ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=65 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=234 ctermbg=34 cterm=NONE
    hi Command ctermfg=176 ctermbg=NONE cterm=NONE
    hi! link QuickFixLine Search
    hi! link Delimiter Special
    hi GitGutterAdd ctermfg=34 ctermbg=NONE cterm=NONE
    hi GitGutterChange ctermfg=223 ctermbg=NONE cterm=NONE
    hi GitGutterChangeDelete ctermfg=223 ctermbg=NONE cterm=NONE
    hi GitGutterDelete ctermfg=196 ctermbg=NONE cterm=NONE
    hi SignifySignAdd ctermfg=34 ctermbg=NONE cterm=NONE
    hi SignifySignChange ctermfg=223 ctermbg=NONE cterm=NONE
    hi SignifySignChangeDelete ctermfg=223 ctermbg=NONE cterm=NONE
    hi SignifySignDelete ctermfg=196 ctermbg=NONE cterm=NONE
    if get(g:Vsd, 'extra_highlight', 1)
      hi! link helpCommand Comment
      hi! link helpSectionDelim Folded
      hi! link helpHeader PreProc
      hi! link helpHeadline Statement
      hi! link helpHyperTextEntry String
      hi! link helpHyperTextJump Identifier
      hi! link helpExample Comment
      hi! link helpOption Type
      hi! link helpSpecial Special
      hi pythonBytesEscape ctermfg=203 ctermbg=NONE cterm=NONE
      hi pythonStrFormat ctermfg=203 ctermbg=NONE cterm=NONE
      hi pythonStrFormatting ctermfg=203 ctermbg=NONE cterm=NONE
      hi! link pythonOperator Statement
      hi cSpecial ctermfg=203 ctermbg=NONE cterm=NONE
      hi! link cBraces Delimiter
    endif
    let g:fzf_colors = { "fg": ["fg", "Normal"], "bg": ["bg", "Normal"], "hl": ["fg", "Conditional"], "fg+": ["fg", "CursorLine", "CursorColumn", "Normal"], "bg+": ["bg", "CursorLine", "CursorColumn"], "hl+": ["fg", "Conditional"], "info": ["fg", "Conditional"], "border": ["fg", "Ignore"], "prompt": ["fg", "Comment"], "pointer": ["fg", "Conditional"], "marker": ["fg", "Conditional"], "spinner": ["fg", "Conditional"], "header": ["fg", "Conditional"] }
    hi FoldColumn ctermfg=39 ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=236 ctermbg=233 cterm=NONE
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Normal ctermfg=234 ctermbg=231 cterm=NONE
  let g:Vsd = get(g:, 'Vsd', {})
  silent! call vsd#init('vslight')
  hi MatchParen ctermfg=196 ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=21 ctermbg=255 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=153 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=255 cterm=NONE
  hi Folded ctermfg=241 ctermbg=255 cterm=NONE
  hi FoldColumn ctermfg=241 ctermbg=255 cterm=NONE
  hi IncSearch ctermfg=125 ctermbg=223 cterm=bold
  hi Search ctermfg=NONE ctermbg=223 cterm=NONE
  hi Question ctermfg=21 ctermbg=223 cterm=NONE
  hi MoreMsg ctermfg=21 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=21 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=32 ctermbg=255 cterm=NONE
  hi StatusLineTerm ctermfg=32 ctermbg=255 cterm=NONE
  hi StatusLineNC ctermfg=fg ctermbg=NONE cterm=NONE
  hi StatusLineTermNC ctermfg=fg ctermbg=NONE cterm=NONE
  hi Error ctermfg=196 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=196 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=196 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=21 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=196 ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=128 ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=32 ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=128 ctermbg=NONE cterm=undercurl
  hi Pmenu ctermfg=236 ctermbg=252 cterm=NONE
  hi PmenuSel ctermfg=252 ctermbg=32 cterm=NONE
  hi PmenuThumb ctermfg=21 ctermbg=21 cterm=NONE
  hi PmenuSbar ctermfg=22 ctermbg=22 cterm=NONE
  hi! link WildMenu PmenuSel
  hi DiffAdd ctermfg=NONE ctermbg=153 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=255 cterm=NONE
  hi DiffDelete ctermfg=196 ctermbg=NONE cterm=bold
  hi DiffText ctermfg=NONE ctermbg=223 cterm=bold
  hi diffFile ctermfg=124 ctermbg=NONE cterm=bold
  hi diffLine ctermfg=125 ctermbg=NONE cterm=italic
  if !s:italics
    hi diffLine cterm=NONE
  endif
  hi diffAdded guifg=#003f00 guibg=#afdfff ctermfg=22 ctermbg=153 gui=none cterm=none
  hi diffChanged guifg=#682900 guibg=#c0c0c0 ctermfg=88 ctermbg=7 gui=none cterm=none
  hi diffRemoved guifg=#a31515 guibg=#afafdf ctermfg=124 ctermbg=146 gui=none cterm=none
  hi SignColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi LineNr ctermfg=241 ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi EndOfBuffer ctermfg=241 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=241 ctermbg=255 cterm=NONE
  hi TabLine ctermfg=fg ctermbg=255 cterm=NONE
  hi TabLineSel ctermfg=255 ctermbg=21 cterm=NONE
  hi TabLineFill ctermfg=fg ctermbg=255 cterm=NONE
  hi ToolbarLine ctermfg=255 ctermbg=21 cterm=NONE
  hi ToolbarButton ctermfg=21 ctermbg=255 cterm=NONE
  hi Constant ctermfg=21 ctermbg=NONE cterm=NONE
  hi String ctermfg=124 ctermbg=NONE cterm=NONE
  hi Number ctermfg=fg ctermbg=NONE cterm=bold
  hi Directory ctermfg=21 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=236 ctermbg=NONE cterm=bold
  hi Function ctermfg=94 ctermbg=NONE cterm=bold
  hi Statement ctermfg=128 ctermbg=NONE cterm=NONE
  hi! link Conditional Statement
  hi! link Repeat Statement
  hi! link Exception Statement
  hi Operator ctermfg=236 ctermbg=NONE cterm=NONE
  hi! link Keyword Statement
  hi PreProc ctermfg=128 ctermbg=NONE cterm=NONE
  hi! link Include PreProc
  hi! link Define PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi Type ctermfg=21 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=128 ctermbg=NONE cterm=underline
  hi Special ctermfg=125 ctermbg=NONE cterm=NONE
  hi! link SpecialKey Special
  hi Delimiter ctermfg=241 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=241 ctermbg=NONE cterm=NONE
  hi Title ctermfg=32 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=28 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=241 ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=22 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=255 ctermbg=21 cterm=NONE
  hi Command ctermfg=128 ctermbg=NONE cterm=NONE
  hi! link QuickFixLine Search
  hi GitGutterAdd ctermfg=22 ctermbg=255 cterm=NONE
  hi GitGutterChange ctermfg=125 ctermbg=255 cterm=NONE
  hi GitGutterChangeDelete ctermfg=125 ctermbg=255 cterm=NONE
  hi GitGutterDelete ctermfg=196 ctermbg=255 cterm=NONE
  hi SignifySignAdd ctermfg=22 ctermbg=255 cterm=NONE
  hi SignifySignChange ctermfg=125 ctermbg=255 cterm=NONE
  hi SignifySignChangeDelete ctermfg=125 ctermbg=255 cterm=NONE
  hi SignifySignDelete ctermfg=196 ctermbg=255 cterm=NONE
  if get(g:Vsd, 'extra_highlight', 1)
    hi! link helpCommand Type
    hi! link helpSectionDelim PreProc
    hi! link HelpHeadline Statement
    hi! link helpHyperTextEntry String
    hi! link HelpHeadline String
    hi pythonBytesEscape ctermfg=125 ctermbg=NONE cterm=NONE
    hi pythonStrFormat ctermfg=125 ctermbg=NONE cterm=NONE
    hi pythonStrFormatting ctermfg=125 ctermbg=NONE cterm=NONE
    hi! link pythonOperator Statement
    hi cSpecial ctermfg=125 ctermbg=NONE cterm=NONE
    hi! link cBraces Delimiter
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color:	black		#1e1e1e		234	Black
" Color:	darkred		#a31515		124	DarkRed
" Color:	darkgreen	#003f00		22	DarkGreen
" Color:	darkyellow	#f8c9ab		223	DarkYellow
" Color:	darkblue	#000080		18	DarkBlue
" Color:	darkmagenta	#af00db		128	DarkMagenta
" Color:	darkcyan	#007ACC		32	DarkCyan
" Color:	lightgray	#f3f3f3		255	LightGray
" Color:	darkgray	#606060		241	DarkGray
" Color:	red		#ff0000		196	Red
" Color:	green		#008000		28	DarkGreen
" Color:	yellow		#f2c38f		223	Yellow
" Color:	blue		#0000ff		21	Blue
" Color:	magenta		#c586c0		176	Magenta
" Color:	cyan		#ADD6FF		153	Cyan
" Color:	background	#ffffff		231	White
" Color:	gray		#cecece		252	LightGray
" Color:	verydark	#333333		236	Black
" Color:	special		#811f3f		125	Brown
" Color:	function	#795E26		94	Brown
" Term Colors: black darkred darkgreen special darkblue darkmagenta darkcyan lightgray
" Term Colors: darkgray red green darkyellow blue darkmagenta darkcyan background
" Background: dark
" Color:	black		#1e1e1e		234	Black
" Color:	darkred		#730b00		88	DarkRed
" Color:	darkgreen	#608b4e		65	DarkGreen
" Color:	darkyellow	#f2c38f		223	Yellow
" Color:	darkblue	#073655		17	DarkBlue
" Color:	purple		#9a93e1		104	Magenta
" Color:	skyblue		#569cd6		39	DarkCyan
" Color:	lightgrey	#a9a9a9		248	LightGray
" Color:	darkgrey	#333233		236	DarkGray
" Color:	red		#ff0000		196	Red
" Color:	lightgreen	#a8ce93		150	Green
" Color:	yellow		#dada93		186	Yellow
" Color:	visual		#204366		19	DarkBlue
" Color:	pink		#c586c0		176	Magenta
" Color:	cyan		#42dcd7		44	Cyan
" Color:	white		#c0d0d0		252	White
" Color:	lightblue	#83afe5		110	DarkCyan
" Color:	nightblue	#212733		235	DarkBlue
" Color:	green		#00af00		34	Green
" Color:	cyangrey	#7fc1ca		109	LightGray
" Color:	grey		#4c4e50		239	DarkGray
" Color:	identifier	#c9c6c9		251	LightGray
" Color:	string		#ce9178		173	Brown
" Color:	lightred	#df8c8c		174	Red
" Color:	softred		#ff5947		203	Red
" Color:	special  	#607b9e		67	DarkBlue
" Color:	zero		#121212		233	Black
" Term Colors: grey lightred lightgreen yellow lightblue purple lightblue identifier
" Term Colors: darkgreen darkyellow lightgreen yellow lightblue pink lightblue white
" vim: et ts=2 sw=2
